### ISSUE TITLE
form.media is empty

### ISSUE THREAD

**Issue by joshuakoh1** [fle/django-jsignature#27]
Hello,

form.media does not load anything when using a ModelForm

```
class TransactionCreateForm(forms.ModelForm):
    signature = JSignatureField()
    class Meta:
        model = models.Transaction
        fields = [ ..., 'signature']
```

The entire field is empty, only showing the reset button. Inspection of source shows that the template does not render anything under {{ form.media }}

**Comment by joshuakoh1** [comment]
It's also not loading in the admin panel for a different reason

```
jQuery.Deferred exception: $ is not a function TypeError: $ is not a function
    at new r (/static/js/jSignature.min.js:41:473)
    at HTMLDivElement.<anonymous> (/static/js/jSignature.min.js:59:219)
    at Function.each (/static/admin/js/vendor/jquery/jquery.min.js:2:2976)
    at S.fn.init.each (/static/admin/js/vendor/jquery/jquery.min.js:2:1454)
    at S.fn.init.init (/static/js/jSignature.min.js:59:135)
    at $.fn.<computed> [as jSignature] (/static/js/jSignature.min.js:60:464)
    at HTMLDivElement.<anonymous> (/static/js/django_jsignature.js:6:15)
    at Function.each (/static/admin/js/vendor/jquery/jquery.min.js:2:2976)
    at S.fn.init.each (/static/admin/js/vendor/jquery/jquery.min.js:2:1454)
    at HTMLDocument.<anonymous> (/static/js/django_jsignature.js:3:27) undefined
    
Uncaught TypeError: $ is not a function
    at new r (jSignature.min.js:41:473)
    at HTMLDivElement.<anonymous> (jSignature.min.js:59:219)
    at Function.each (jquery.min.js:2:2976)
    at S.fn.init.each (jquery.min.js:2:1454)
    at S.fn.init.init (jSignature.min.js:59:135)
    at $.fn.<computed> [as jSignature] (jSignature.min.js:60:464)
    at HTMLDivElement.<anonymous> (django_jsignature.js:6:15)
    at Function.each (jquery.min.js:2:2976)
    at S.fn.init.each (jquery.min.js:2:1454)
    at HTMLDocument.<anonymous> (django_jsignature.js:3:27)
```

Loading order of jquery in the admin panel is before everything else:

```
  | <script src="/static/admin/js/vendor/jquery/jquery.min.js"></script>
  | <script src="/static/js/jSignature.min.js"></script>
  | <script src="/static/admin/js/jquery.init.js"></script>
  | <script src="/static/js/django_jsignature.js"></script>
  | <script src="/static/admin/js/core.js"></script>
  | <script src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
  | <script src="/static/admin/js/actions.js"></script>
  | <script src="/static/admin/js/urlify.js"></script>
  | <script src="/static/admin/js/prepopulate.js"></script>
  | <script src="/static/admin/js/vendor/xregexp/xregexp.min.js"></script>
</script>

**Comment by joshuakoh1** [comment]
Fixed it by manually adding the files to the page template but would be nice to know why it didn't work
```
<script src="{% static 'js/jSignature.min.js' %}"></script>
<script src="{% static 'js/django_jsignature.js' %}"></script>
```

**Comment by SebCorbin** [comment]
Added test and could not reproduce
